// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: user/api/auth/v1/auth.proto

package v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on RegisterAuthRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RegisterAuthRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterAuthRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterAuthRequestMultiError, or nil if none found.
func (m *RegisterAuthRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterAuthRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RegisterAuthRequestMultiError(errors)
	}
	return nil
}

// RegisterAuthRequestMultiError is an error wrapping multiple validation
// errors returned by RegisterAuthRequest.ValidateAll() if the designated
// constraints aren't met.
type RegisterAuthRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterAuthRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterAuthRequestMultiError) AllErrors() []error { return m }

// RegisterAuthRequestValidationError is the validation error returned by
// RegisterAuthRequest.Validate if the designated constraints aren't met.
type RegisterAuthRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterAuthRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterAuthRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterAuthRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterAuthRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterAuthRequestValidationError) ErrorName() string {
	return "RegisterAuthRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterAuthRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterAuthRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterAuthRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterAuthRequestValidationError{}

// Validate checks the field values on RegisterAuthReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *RegisterAuthReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RegisterAuthReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RegisterAuthReplyMultiError, or nil if none found.
func (m *RegisterAuthReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RegisterAuthReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return RegisterAuthReplyMultiError(errors)
	}
	return nil
}

// RegisterAuthReplyMultiError is an error wrapping multiple validation errors
// returned by RegisterAuthReply.ValidateAll() if the designated constraints
// aren't met.
type RegisterAuthReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RegisterAuthReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RegisterAuthReplyMultiError) AllErrors() []error { return m }

// RegisterAuthReplyValidationError is the validation error returned by
// RegisterAuthReply.Validate if the designated constraints aren't met.
type RegisterAuthReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RegisterAuthReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RegisterAuthReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RegisterAuthReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RegisterAuthReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RegisterAuthReplyValidationError) ErrorName() string {
	return "RegisterAuthReplyValidationError"
}

// Error satisfies the builtin error interface
func (e RegisterAuthReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRegisterAuthReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RegisterAuthReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RegisterAuthReplyValidationError{}

// Validate checks the field values on LoginAuthRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *LoginAuthRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginAuthRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LoginAuthRequestMultiError, or nil if none found.
func (m *LoginAuthRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginAuthRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetUsername()) < 1 {
		err := LoginAuthRequestValidationError{
			field:  "Username",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPassword()) < 1 {
		err := LoginAuthRequestValidationError{
			field:  "Password",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Remember

	if len(errors) > 0 {
		return LoginAuthRequestMultiError(errors)
	}
	return nil
}

// LoginAuthRequestMultiError is an error wrapping multiple validation errors
// returned by LoginAuthRequest.ValidateAll() if the designated constraints
// aren't met.
type LoginAuthRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginAuthRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginAuthRequestMultiError) AllErrors() []error { return m }

// LoginAuthRequestValidationError is the validation error returned by
// LoginAuthRequest.Validate if the designated constraints aren't met.
type LoginAuthRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginAuthRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginAuthRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginAuthRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginAuthRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginAuthRequestValidationError) ErrorName() string { return "LoginAuthRequestValidationError" }

// Error satisfies the builtin error interface
func (e LoginAuthRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginAuthRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginAuthRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginAuthRequestValidationError{}

// Validate checks the field values on TokenRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TokenRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TokenRequestMultiError, or
// nil if none found.
func (m *TokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *TokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if _, ok := _TokenRequest_GrantType_InLookup[m.GetGrantType()]; !ok {
		err := TokenRequestValidationError{
			field:  "GrantType",
			reason: "value must be in list [ password refresh_token authorization_code]",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	// no validation rules for Username

	// no validation rules for Password

	// no validation rules for RefreshToken

	if len(errors) > 0 {
		return TokenRequestMultiError(errors)
	}
	return nil
}

// TokenRequestMultiError is an error wrapping multiple validation errors
// returned by TokenRequest.ValidateAll() if the designated constraints aren't met.
type TokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TokenRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TokenRequestMultiError) AllErrors() []error { return m }

// TokenRequestValidationError is the validation error returned by
// TokenRequest.Validate if the designated constraints aren't met.
type TokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TokenRequestValidationError) ErrorName() string { return "TokenRequestValidationError" }

// Error satisfies the builtin error interface
func (e TokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TokenRequestValidationError{}

var _TokenRequest_GrantType_InLookup = map[string]struct{}{
	"":                   {},
	"password":           {},
	"refresh_token":      {},
	"authorization_code": {},
}

// Validate checks the field values on TokenReply with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *TokenReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on TokenReply with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in TokenReplyMultiError, or
// nil if none found.
func (m *TokenReply) ValidateAll() error {
	return m.validate(true)
}

func (m *TokenReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccessToken

	// no validation rules for TokenType

	// no validation rules for RefreshToken

	// no validation rules for ExpiresIn

	if len(errors) > 0 {
		return TokenReplyMultiError(errors)
	}
	return nil
}

// TokenReplyMultiError is an error wrapping multiple validation errors
// returned by TokenReply.ValidateAll() if the designated constraints aren't met.
type TokenReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m TokenReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m TokenReplyMultiError) AllErrors() []error { return m }

// TokenReplyValidationError is the validation error returned by
// TokenReply.Validate if the designated constraints aren't met.
type TokenReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e TokenReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e TokenReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e TokenReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e TokenReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e TokenReplyValidationError) ErrorName() string { return "TokenReplyValidationError" }

// Error satisfies the builtin error interface
func (e TokenReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sTokenReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = TokenReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = TokenReplyValidationError{}

// Validate checks the field values on LoginAuthReply with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LoginAuthReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginAuthReply with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LoginAuthReplyMultiError,
// or nil if none found.
func (m *LoginAuthReply) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginAuthReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccessToken

	// no validation rules for TokenType

	// no validation rules for Expires

	// no validation rules for RefreshToken

	// no validation rules for ExpiresIn

	if len(errors) > 0 {
		return LoginAuthReplyMultiError(errors)
	}
	return nil
}

// LoginAuthReplyMultiError is an error wrapping multiple validation errors
// returned by LoginAuthReply.ValidateAll() if the designated constraints
// aren't met.
type LoginAuthReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginAuthReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginAuthReplyMultiError) AllErrors() []error { return m }

// LoginAuthReplyValidationError is the validation error returned by
// LoginAuthReply.Validate if the designated constraints aren't met.
type LoginAuthReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginAuthReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginAuthReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginAuthReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginAuthReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginAuthReplyValidationError) ErrorName() string { return "LoginAuthReplyValidationError" }

// Error satisfies the builtin error interface
func (e LoginAuthReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginAuthReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginAuthReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginAuthReplyValidationError{}

// Validate checks the field values on RefreshTokenAuthRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RefreshTokenAuthRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RefreshTokenAuthRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RefreshTokenAuthRequestMultiError, or nil if none found.
func (m *RefreshTokenAuthRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *RefreshTokenAuthRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if utf8.RuneCountInString(m.GetRefreshToken()) < 1 {
		err := RefreshTokenAuthRequestValidationError{
			field:  "RefreshToken",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return RefreshTokenAuthRequestMultiError(errors)
	}
	return nil
}

// RefreshTokenAuthRequestMultiError is an error wrapping multiple validation
// errors returned by RefreshTokenAuthRequest.ValidateAll() if the designated
// constraints aren't met.
type RefreshTokenAuthRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefreshTokenAuthRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefreshTokenAuthRequestMultiError) AllErrors() []error { return m }

// RefreshTokenAuthRequestValidationError is the validation error returned by
// RefreshTokenAuthRequest.Validate if the designated constraints aren't met.
type RefreshTokenAuthRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefreshTokenAuthRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefreshTokenAuthRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefreshTokenAuthRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefreshTokenAuthRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefreshTokenAuthRequestValidationError) ErrorName() string {
	return "RefreshTokenAuthRequestValidationError"
}

// Error satisfies the builtin error interface
func (e RefreshTokenAuthRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefreshTokenAuthRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefreshTokenAuthRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefreshTokenAuthRequestValidationError{}

// Validate checks the field values on RefreshTokenAuthReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *RefreshTokenAuthReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on RefreshTokenAuthReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// RefreshTokenAuthReplyMultiError, or nil if none found.
func (m *RefreshTokenAuthReply) ValidateAll() error {
	return m.validate(true)
}

func (m *RefreshTokenAuthReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccessToken

	// no validation rules for TokenType

	// no validation rules for RefreshToken

	// no validation rules for ExpiresIn

	if len(errors) > 0 {
		return RefreshTokenAuthReplyMultiError(errors)
	}
	return nil
}

// RefreshTokenAuthReplyMultiError is an error wrapping multiple validation
// errors returned by RefreshTokenAuthReply.ValidateAll() if the designated
// constraints aren't met.
type RefreshTokenAuthReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m RefreshTokenAuthReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m RefreshTokenAuthReplyMultiError) AllErrors() []error { return m }

// RefreshTokenAuthReplyValidationError is the validation error returned by
// RefreshTokenAuthReply.Validate if the designated constraints aren't met.
type RefreshTokenAuthReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e RefreshTokenAuthReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e RefreshTokenAuthReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e RefreshTokenAuthReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e RefreshTokenAuthReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e RefreshTokenAuthReplyValidationError) ErrorName() string {
	return "RefreshTokenAuthReplyValidationError"
}

// Error satisfies the builtin error interface
func (e RefreshTokenAuthReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sRefreshTokenAuthReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = RefreshTokenAuthReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = RefreshTokenAuthReplyValidationError{}

// Validate checks the field values on PasswordlessTokenAuthRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PasswordlessTokenAuthRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PasswordlessTokenAuthRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PasswordlessTokenAuthRequestMultiError, or nil if none found.
func (m *PasswordlessTokenAuthRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *PasswordlessTokenAuthRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PasswordlessTokenAuthRequestMultiError(errors)
	}
	return nil
}

// PasswordlessTokenAuthRequestMultiError is an error wrapping multiple
// validation errors returned by PasswordlessTokenAuthRequest.ValidateAll() if
// the designated constraints aren't met.
type PasswordlessTokenAuthRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PasswordlessTokenAuthRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PasswordlessTokenAuthRequestMultiError) AllErrors() []error { return m }

// PasswordlessTokenAuthRequestValidationError is the validation error returned
// by PasswordlessTokenAuthRequest.Validate if the designated constraints
// aren't met.
type PasswordlessTokenAuthRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PasswordlessTokenAuthRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PasswordlessTokenAuthRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PasswordlessTokenAuthRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PasswordlessTokenAuthRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PasswordlessTokenAuthRequestValidationError) ErrorName() string {
	return "PasswordlessTokenAuthRequestValidationError"
}

// Error satisfies the builtin error interface
func (e PasswordlessTokenAuthRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPasswordlessTokenAuthRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PasswordlessTokenAuthRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PasswordlessTokenAuthRequestValidationError{}

// Validate checks the field values on PasswordlessTokenAuthReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *PasswordlessTokenAuthReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on PasswordlessTokenAuthReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// PasswordlessTokenAuthReplyMultiError, or nil if none found.
func (m *PasswordlessTokenAuthReply) ValidateAll() error {
	return m.validate(true)
}

func (m *PasswordlessTokenAuthReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return PasswordlessTokenAuthReplyMultiError(errors)
	}
	return nil
}

// PasswordlessTokenAuthReplyMultiError is an error wrapping multiple
// validation errors returned by PasswordlessTokenAuthReply.ValidateAll() if
// the designated constraints aren't met.
type PasswordlessTokenAuthReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m PasswordlessTokenAuthReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m PasswordlessTokenAuthReplyMultiError) AllErrors() []error { return m }

// PasswordlessTokenAuthReplyValidationError is the validation error returned
// by PasswordlessTokenAuthReply.Validate if the designated constraints aren't met.
type PasswordlessTokenAuthReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e PasswordlessTokenAuthReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e PasswordlessTokenAuthReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e PasswordlessTokenAuthReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e PasswordlessTokenAuthReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e PasswordlessTokenAuthReplyValidationError) ErrorName() string {
	return "PasswordlessTokenAuthReplyValidationError"
}

// Error satisfies the builtin error interface
func (e PasswordlessTokenAuthReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sPasswordlessTokenAuthReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = PasswordlessTokenAuthReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = PasswordlessTokenAuthReplyValidationError{}

// Validate checks the field values on LoginPasswordlessRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *LoginPasswordlessRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginPasswordlessRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LoginPasswordlessRequestMultiError, or nil if none found.
func (m *LoginPasswordlessRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginPasswordlessRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return LoginPasswordlessRequestMultiError(errors)
	}
	return nil
}

// LoginPasswordlessRequestMultiError is an error wrapping multiple validation
// errors returned by LoginPasswordlessRequest.ValidateAll() if the designated
// constraints aren't met.
type LoginPasswordlessRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginPasswordlessRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginPasswordlessRequestMultiError) AllErrors() []error { return m }

// LoginPasswordlessRequestValidationError is the validation error returned by
// LoginPasswordlessRequest.Validate if the designated constraints aren't met.
type LoginPasswordlessRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginPasswordlessRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginPasswordlessRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginPasswordlessRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginPasswordlessRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginPasswordlessRequestValidationError) ErrorName() string {
	return "LoginPasswordlessRequestValidationError"
}

// Error satisfies the builtin error interface
func (e LoginPasswordlessRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginPasswordlessRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginPasswordlessRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginPasswordlessRequestValidationError{}

// Validate checks the field values on LoginPasswordlessReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *LoginPasswordlessReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LoginPasswordlessReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// LoginPasswordlessReplyMultiError, or nil if none found.
func (m *LoginPasswordlessReply) ValidateAll() error {
	return m.validate(true)
}

func (m *LoginPasswordlessReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return LoginPasswordlessReplyMultiError(errors)
	}
	return nil
}

// LoginPasswordlessReplyMultiError is an error wrapping multiple validation
// errors returned by LoginPasswordlessReply.ValidateAll() if the designated
// constraints aren't met.
type LoginPasswordlessReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginPasswordlessReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginPasswordlessReplyMultiError) AllErrors() []error { return m }

// LoginPasswordlessReplyValidationError is the validation error returned by
// LoginPasswordlessReply.Validate if the designated constraints aren't met.
type LoginPasswordlessReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginPasswordlessReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginPasswordlessReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginPasswordlessReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginPasswordlessReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginPasswordlessReplyValidationError) ErrorName() string {
	return "LoginPasswordlessReplyValidationError"
}

// Error satisfies the builtin error interface
func (e LoginPasswordlessReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLoginPasswordlessReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginPasswordlessReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginPasswordlessReplyValidationError{}

// Validate checks the field values on ForgetPasswordTokenRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ForgetPasswordTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ForgetPasswordTokenRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ForgetPasswordTokenRequestMultiError, or nil if none found.
func (m *ForgetPasswordTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ForgetPasswordTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetPhone()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ForgetPasswordTokenRequestValidationError{
					field:  "Phone",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ForgetPasswordTokenRequestValidationError{
					field:  "Phone",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetPhone()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ForgetPasswordTokenRequestValidationError{
				field:  "Phone",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetEmail()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ForgetPasswordTokenRequestValidationError{
					field:  "Email",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ForgetPasswordTokenRequestValidationError{
					field:  "Email",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetEmail()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ForgetPasswordTokenRequestValidationError{
				field:  "Email",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ForgetPasswordTokenRequestMultiError(errors)
	}
	return nil
}

// ForgetPasswordTokenRequestMultiError is an error wrapping multiple
// validation errors returned by ForgetPasswordTokenRequest.ValidateAll() if
// the designated constraints aren't met.
type ForgetPasswordTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ForgetPasswordTokenRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ForgetPasswordTokenRequestMultiError) AllErrors() []error { return m }

// ForgetPasswordTokenRequestValidationError is the validation error returned
// by ForgetPasswordTokenRequest.Validate if the designated constraints aren't met.
type ForgetPasswordTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ForgetPasswordTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ForgetPasswordTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ForgetPasswordTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ForgetPasswordTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ForgetPasswordTokenRequestValidationError) ErrorName() string {
	return "ForgetPasswordTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ForgetPasswordTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sForgetPasswordTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ForgetPasswordTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ForgetPasswordTokenRequestValidationError{}

// Validate checks the field values on ForgetPasswordTokenReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ForgetPasswordTokenReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ForgetPasswordTokenReply with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ForgetPasswordTokenReplyMultiError, or nil if none found.
func (m *ForgetPasswordTokenReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ForgetPasswordTokenReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ForgetPasswordTokenReplyMultiError(errors)
	}
	return nil
}

// ForgetPasswordTokenReplyMultiError is an error wrapping multiple validation
// errors returned by ForgetPasswordTokenReply.ValidateAll() if the designated
// constraints aren't met.
type ForgetPasswordTokenReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ForgetPasswordTokenReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ForgetPasswordTokenReplyMultiError) AllErrors() []error { return m }

// ForgetPasswordTokenReplyValidationError is the validation error returned by
// ForgetPasswordTokenReply.Validate if the designated constraints aren't met.
type ForgetPasswordTokenReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ForgetPasswordTokenReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ForgetPasswordTokenReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ForgetPasswordTokenReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ForgetPasswordTokenReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ForgetPasswordTokenReplyValidationError) ErrorName() string {
	return "ForgetPasswordTokenReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ForgetPasswordTokenReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sForgetPasswordTokenReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ForgetPasswordTokenReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ForgetPasswordTokenReplyValidationError{}

// Validate checks the field values on ForgetPasswordRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ForgetPasswordRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ForgetPasswordRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ForgetPasswordRequestMultiError, or nil if none found.
func (m *ForgetPasswordRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ForgetPasswordRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ForgetPasswordRequestMultiError(errors)
	}
	return nil
}

// ForgetPasswordRequestMultiError is an error wrapping multiple validation
// errors returned by ForgetPasswordRequest.ValidateAll() if the designated
// constraints aren't met.
type ForgetPasswordRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ForgetPasswordRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ForgetPasswordRequestMultiError) AllErrors() []error { return m }

// ForgetPasswordRequestValidationError is the validation error returned by
// ForgetPasswordRequest.Validate if the designated constraints aren't met.
type ForgetPasswordRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ForgetPasswordRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ForgetPasswordRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ForgetPasswordRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ForgetPasswordRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ForgetPasswordRequestValidationError) ErrorName() string {
	return "ForgetPasswordRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ForgetPasswordRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sForgetPasswordRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ForgetPasswordRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ForgetPasswordRequestValidationError{}

// Validate checks the field values on ForgetPasswordReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ForgetPasswordReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ForgetPasswordReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ForgetPasswordReplyMultiError, or nil if none found.
func (m *ForgetPasswordReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ForgetPasswordReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return ForgetPasswordReplyMultiError(errors)
	}
	return nil
}

// ForgetPasswordReplyMultiError is an error wrapping multiple validation
// errors returned by ForgetPasswordReply.ValidateAll() if the designated
// constraints aren't met.
type ForgetPasswordReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ForgetPasswordReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ForgetPasswordReplyMultiError) AllErrors() []error { return m }

// ForgetPasswordReplyValidationError is the validation error returned by
// ForgetPasswordReply.Validate if the designated constraints aren't met.
type ForgetPasswordReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ForgetPasswordReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ForgetPasswordReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ForgetPasswordReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ForgetPasswordReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ForgetPasswordReplyValidationError) ErrorName() string {
	return "ForgetPasswordReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ForgetPasswordReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sForgetPasswordReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ForgetPasswordReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ForgetPasswordReplyValidationError{}

// Validate checks the field values on ValidatePasswordRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ValidatePasswordRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ValidatePasswordRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ValidatePasswordRequestMultiError, or nil if none found.
func (m *ValidatePasswordRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *ValidatePasswordRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Password

	if len(errors) > 0 {
		return ValidatePasswordRequestMultiError(errors)
	}
	return nil
}

// ValidatePasswordRequestMultiError is an error wrapping multiple validation
// errors returned by ValidatePasswordRequest.ValidateAll() if the designated
// constraints aren't met.
type ValidatePasswordRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ValidatePasswordRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ValidatePasswordRequestMultiError) AllErrors() []error { return m }

// ValidatePasswordRequestValidationError is the validation error returned by
// ValidatePasswordRequest.Validate if the designated constraints aren't met.
type ValidatePasswordRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ValidatePasswordRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ValidatePasswordRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ValidatePasswordRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ValidatePasswordRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ValidatePasswordRequestValidationError) ErrorName() string {
	return "ValidatePasswordRequestValidationError"
}

// Error satisfies the builtin error interface
func (e ValidatePasswordRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sValidatePasswordRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ValidatePasswordRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ValidatePasswordRequestValidationError{}

// Validate checks the field values on ValidatePasswordReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *ValidatePasswordReply) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ValidatePasswordReply with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// ValidatePasswordReplyMultiError, or nil if none found.
func (m *ValidatePasswordReply) ValidateAll() error {
	return m.validate(true)
}

func (m *ValidatePasswordReply) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Ok

	if len(errors) > 0 {
		return ValidatePasswordReplyMultiError(errors)
	}
	return nil
}

// ValidatePasswordReplyMultiError is an error wrapping multiple validation
// errors returned by ValidatePasswordReply.ValidateAll() if the designated
// constraints aren't met.
type ValidatePasswordReplyMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ValidatePasswordReplyMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ValidatePasswordReplyMultiError) AllErrors() []error { return m }

// ValidatePasswordReplyValidationError is the validation error returned by
// ValidatePasswordReply.Validate if the designated constraints aren't met.
type ValidatePasswordReplyValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ValidatePasswordReplyValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ValidatePasswordReplyValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ValidatePasswordReplyValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ValidatePasswordReplyValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ValidatePasswordReplyValidationError) ErrorName() string {
	return "ValidatePasswordReplyValidationError"
}

// Error satisfies the builtin error interface
func (e ValidatePasswordReplyValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sValidatePasswordReply.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ValidatePasswordReplyValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ValidatePasswordReplyValidationError{}

// Validate checks the field values on GetLoginFormRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetLoginFormRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLoginFormRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetLoginFormRequestMultiError, or nil if none found.
func (m *GetLoginFormRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLoginFormRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Redirect

	if len(errors) > 0 {
		return GetLoginFormRequestMultiError(errors)
	}
	return nil
}

// GetLoginFormRequestMultiError is an error wrapping multiple validation
// errors returned by GetLoginFormRequest.ValidateAll() if the designated
// constraints aren't met.
type GetLoginFormRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLoginFormRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLoginFormRequestMultiError) AllErrors() []error { return m }

// GetLoginFormRequestValidationError is the validation error returned by
// GetLoginFormRequest.Validate if the designated constraints aren't met.
type GetLoginFormRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLoginFormRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLoginFormRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLoginFormRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLoginFormRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLoginFormRequestValidationError) ErrorName() string {
	return "GetLoginFormRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetLoginFormRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLoginFormRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLoginFormRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLoginFormRequestValidationError{}

// Validate checks the field values on GetLoginFormResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetLoginFormResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetLoginFormResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetLoginFormResponseMultiError, or nil if none found.
func (m *GetLoginFormResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetLoginFormResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Redirect

	for idx, item := range m.GetOauth() {
		_, _ = idx, item

		if all {
			switch v := interface{}(item).(type) {
			case interface{ ValidateAll() error }:
				if err := v.ValidateAll(); err != nil {
					errors = append(errors, GetLoginFormResponseValidationError{
						field:  fmt.Sprintf("Oauth[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			case interface{ Validate() error }:
				if err := v.Validate(); err != nil {
					errors = append(errors, GetLoginFormResponseValidationError{
						field:  fmt.Sprintf("Oauth[%v]", idx),
						reason: "embedded message failed validation",
						cause:  err,
					})
				}
			}
		} else if v, ok := interface{}(item).(interface{ Validate() error }); ok {
			if err := v.Validate(); err != nil {
				return GetLoginFormResponseValidationError{
					field:  fmt.Sprintf("Oauth[%v]", idx),
					reason: "embedded message failed validation",
					cause:  err,
				}
			}
		}

	}

	if len(errors) > 0 {
		return GetLoginFormResponseMultiError(errors)
	}
	return nil
}

// GetLoginFormResponseMultiError is an error wrapping multiple validation
// errors returned by GetLoginFormResponse.ValidateAll() if the designated
// constraints aren't met.
type GetLoginFormResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetLoginFormResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetLoginFormResponseMultiError) AllErrors() []error { return m }

// GetLoginFormResponseValidationError is the validation error returned by
// GetLoginFormResponse.Validate if the designated constraints aren't met.
type GetLoginFormResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetLoginFormResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetLoginFormResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetLoginFormResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetLoginFormResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetLoginFormResponseValidationError) ErrorName() string {
	return "GetLoginFormResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetLoginFormResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetLoginFormResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetLoginFormResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetLoginFormResponseValidationError{}

// Validate checks the field values on OAuthProvider with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *OAuthProvider) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on OAuthProvider with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in OAuthProviderMultiError, or
// nil if none found.
func (m *OAuthProvider) ValidateAll() error {
	return m.validate(true)
}

func (m *OAuthProvider) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Name

	if len(errors) > 0 {
		return OAuthProviderMultiError(errors)
	}
	return nil
}

// OAuthProviderMultiError is an error wrapping multiple validation errors
// returned by OAuthProvider.ValidateAll() if the designated constraints
// aren't met.
type OAuthProviderMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m OAuthProviderMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m OAuthProviderMultiError) AllErrors() []error { return m }

// OAuthProviderValidationError is the validation error returned by
// OAuthProvider.Validate if the designated constraints aren't met.
type OAuthProviderValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e OAuthProviderValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e OAuthProviderValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e OAuthProviderValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e OAuthProviderValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e OAuthProviderValidationError) ErrorName() string { return "OAuthProviderValidationError" }

// Error satisfies the builtin error interface
func (e OAuthProviderValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sOAuthProvider.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = OAuthProviderValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = OAuthProviderValidationError{}

// Validate checks the field values on GetCsrfTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCsrfTokenRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCsrfTokenRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCsrfTokenRequestMultiError, or nil if none found.
func (m *GetCsrfTokenRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCsrfTokenRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return GetCsrfTokenRequestMultiError(errors)
	}
	return nil
}

// GetCsrfTokenRequestMultiError is an error wrapping multiple validation
// errors returned by GetCsrfTokenRequest.ValidateAll() if the designated
// constraints aren't met.
type GetCsrfTokenRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCsrfTokenRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCsrfTokenRequestMultiError) AllErrors() []error { return m }

// GetCsrfTokenRequestValidationError is the validation error returned by
// GetCsrfTokenRequest.Validate if the designated constraints aren't met.
type GetCsrfTokenRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCsrfTokenRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCsrfTokenRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCsrfTokenRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCsrfTokenRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCsrfTokenRequestValidationError) ErrorName() string {
	return "GetCsrfTokenRequestValidationError"
}

// Error satisfies the builtin error interface
func (e GetCsrfTokenRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCsrfTokenRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCsrfTokenRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCsrfTokenRequestValidationError{}

// Validate checks the field values on GetCsrfTokenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *GetCsrfTokenResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on GetCsrfTokenResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// GetCsrfTokenResponseMultiError, or nil if none found.
func (m *GetCsrfTokenResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *GetCsrfTokenResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for CsrfToken

	if len(errors) > 0 {
		return GetCsrfTokenResponseMultiError(errors)
	}
	return nil
}

// GetCsrfTokenResponseMultiError is an error wrapping multiple validation
// errors returned by GetCsrfTokenResponse.ValidateAll() if the designated
// constraints aren't met.
type GetCsrfTokenResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m GetCsrfTokenResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m GetCsrfTokenResponseMultiError) AllErrors() []error { return m }

// GetCsrfTokenResponseValidationError is the validation error returned by
// GetCsrfTokenResponse.Validate if the designated constraints aren't met.
type GetCsrfTokenResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e GetCsrfTokenResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e GetCsrfTokenResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e GetCsrfTokenResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e GetCsrfTokenResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e GetCsrfTokenResponseValidationError) ErrorName() string {
	return "GetCsrfTokenResponseValidationError"
}

// Error satisfies the builtin error interface
func (e GetCsrfTokenResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sGetCsrfTokenResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = GetCsrfTokenResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = GetCsrfTokenResponseValidationError{}

// Validate checks the field values on LogoutRequest with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LogoutRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogoutRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LogoutRequestMultiError, or
// nil if none found.
func (m *LogoutRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *LogoutRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return LogoutRequestMultiError(errors)
	}
	return nil
}

// LogoutRequestMultiError is an error wrapping multiple validation errors
// returned by LogoutRequest.ValidateAll() if the designated constraints
// aren't met.
type LogoutRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogoutRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogoutRequestMultiError) AllErrors() []error { return m }

// LogoutRequestValidationError is the validation error returned by
// LogoutRequest.Validate if the designated constraints aren't met.
type LogoutRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogoutRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogoutRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogoutRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogoutRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogoutRequestValidationError) ErrorName() string { return "LogoutRequestValidationError" }

// Error satisfies the builtin error interface
func (e LogoutRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogoutRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogoutRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogoutRequestValidationError{}

// Validate checks the field values on LogoutResponse with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LogoutResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LogoutResponse with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LogoutResponseMultiError,
// or nil if none found.
func (m *LogoutResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *LogoutResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return LogoutResponseMultiError(errors)
	}
	return nil
}

// LogoutResponseMultiError is an error wrapping multiple validation errors
// returned by LogoutResponse.ValidateAll() if the designated constraints
// aren't met.
type LogoutResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LogoutResponseMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LogoutResponseMultiError) AllErrors() []error { return m }

// LogoutResponseValidationError is the validation error returned by
// LogoutResponse.Validate if the designated constraints aren't met.
type LogoutResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LogoutResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LogoutResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LogoutResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LogoutResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LogoutResponseValidationError) ErrorName() string { return "LogoutResponseValidationError" }

// Error satisfies the builtin error interface
func (e LogoutResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogoutResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LogoutResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LogoutResponseValidationError{}
